CREATE TABLE IF NOT EXISTS comment_closure (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ancestor_id BIGINT NULL REFERENCES comment(id),
    descendant_id BIGINT NOT NULL REFERENCES comment(id)
);