// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
}

type AuthToken struct {
	AccessToken string `json:"accessToken"`
	ExpiredAt   string `json:"expiredAt"`
}

type CreateCommentInput struct {
	PostID          string `json:"postId"`
	ParentCommentID string `json:"parentCommentId"`
	Content         string `json:"content"`
}

type CreatePostInput struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	IsCommented bool   `json:"IsCommented"`
}

type Mutation struct {
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
